"""
Django settings for newsbsy project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from dotenv import load_dotenv
import os

load_dotenv()
DJANGO_SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
print(DJANGO_SECRET_KEY)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR=os.path.join(BASE_DIR,'templates')
STATIC_DIR=os.path.join(BASE_DIR,'static')


# Quick-start  settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'sbsy.co.in','www.sbsy.co.in',"103.129.97.81"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
     'school',
      'django_cleanup',
]


EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newsbsy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newsbsy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, os.getenv("DB_PATH")),
    }
}


# DATABASES = {
 
#     'default': {
 
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
 
#         'NAME': 'postgres',
 
#         'USER': 'postgres',
 
#         'PASSWORD': 'password_12345',
 
#         'HOST': 'database-1.cluster-cg1nzot3zqcy.us-east-2.rds.amazonaws.com',
 
#         'PORT': 5432,
 
#     }
 
# }


# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql', 
#        'NAME': 'school',
#        'USER': 'root',
#        'PASSWORD': 'nilmani123',
#        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
#        'PORT': '3306',
#    }
# }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True
#USE_L10N = False

USE_TZ = True
#USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = '/static/'
# MEDIA_URL = '/media/'
# STATICFILES_DIRS = [BASE_DIR+"/assets",]
# #STATIC_ROOT = '/home2/sbsycoin/newsbsy/static'
# #MEDIA_ROOT = '/home2/sbsycoin/newsbsy/media'
# STATIC_ROOT = '/home2/sbsycoin/public_html/static'
# MEDIA_ROOT = '/home2/sbsycoin/public_html/media'

# from django.conf.global_settings import DATETIME_INPUT_FORMATS, DATE_INPUT_FORMATS
# DATE_INPUT_FORMATS += ("%d-%m-%Y",)
# DATETIME_INPUT_FORMATS += ("%d-%m-%Y %H:%M:%S",)

# STATIC_URL = '/static/'
# STATICFILES_DIRS=[STATIC_DIR,]
#STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')



import _locale
_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'staticfiles'), ]

DEFAULT_AUTO_FIELD='django.db.models.AutoField'