# Generated by Django 3.0.2 on 2020-08-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
