# Generated by Django 3.0.2 on 2020-08-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notice',
        ),
        migrations.DeleteModel(
            name='notice_board',
        ),
    ]
