# Generated by Django 3.0.2 on 2020-08-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_notice_board'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notice_board',
            new_name='notice',
        ),
    ]
