# Generated by Django 3.0.2 on 2020-08-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200822_1527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notice',
            new_name='notice_board_school',
        ),
    ]
