# Generated by Django 3.0.2 on 2020-08-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200822_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notice_board_school',
        ),
    ]
