# Generated by Django 3.0.2 on 2020-08-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_notice_board_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notice_board_school',
        ),
    ]
