# Generated by Django 3.0.2 on 2020-08-22 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_notice_board_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_board_school',
            name='Time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
