# Generated by Django 3.0.2 on 2020-08-22 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_notice_board_school_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice_board_school',
            name='Time',
        ),
        migrations.AddField(
            model_name='notice_board_school',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
