# Generated by Django 3.0.2 on 2020-08-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200823_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notice_board_school',
        ),
    ]
