# Generated by Django 3.0.2 on 2020-08-24 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_notice_board_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_code', models.CharField(blank=True, max_length=200, null=True)),
                ('Vehicle_Number', models.CharField(blank=True, max_length=200, null=True)),
                ('Driver_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=200, null=True)),
                ('License_Number', models.CharField(blank=True, max_length=200, null=True)),
                ('Route_Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notice_board_school',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
