# Generated by Django 3.0.2 on 2020-08-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_school_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_holiday',
            fields=[
                ('school_holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_code', models.CharField(blank=True, max_length=200, null=True)),
                ('holiday_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
