# Generated by Django 3.0.2 on 2020-09-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_school_holiday_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermaster',
            name='owner_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentsmaster',
            name='Parents_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolmaster',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmaster',
            name='staff_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
