# Generated by Django 3.0.2 on 2020-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20200916_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board_school',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
