# Generated by Django 3.0.2 on 2020-09-16 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20200916_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_holiday',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='school_library',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
