# Generated by Django 3.1.1 on 2020-10-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_message_pack_quary_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_command',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_contact', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('command', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_no', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
