# Generated by Django 3.1.1 on 2020-10-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_user_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='gpsrestapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_no', models.CharField(max_length=200)),
                ('sim_no', models.CharField(max_length=100)),
                ('log', models.CharField(max_length=64)),
                ('lat', models.CharField(max_length=64)),
                ('datetime', models.CharField(max_length=64)),
            ],
        ),
    ]
