# Generated by Django 3.1.1 on 2021-01-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_bikeapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='pumpapi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volt1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volt2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volt3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('relay1', models.CharField(blank=True, max_length=100, null=True)),
                ('relay2', models.CharField(blank=True, max_length=100, null=True)),
                ('relay3', models.CharField(blank=True, max_length=100, null=True)),
                ('temp', models.CharField(blank=True, max_length=20, null=True)),
                ('tank1_waterlevel', models.CharField(blank=True, max_length=20, null=True)),
                ('tank2_waterlevel', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
