# Generated by Django 3.1.6 on 2021-02-04 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20210202_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_machine_api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('school_code', models.CharField(blank=True, max_length=200, null=True)),
                ('gwid', models.CharField(blank=True, max_length=200, null=True)),
                ('ssid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='school_machine_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('school_code', models.CharField(blank=True, max_length=200, null=True)),
                ('gwid', models.CharField(blank=True, max_length=200, null=True)),
                ('ssid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='school_machine_update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('school_code', models.CharField(blank=True, max_length=200, null=True)),
                ('gwid', models.CharField(blank=True, max_length=200, null=True)),
                ('ssid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='parentsmaster',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolmaster',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staffmaster',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentmaster',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
