# Generated by Django 3.1.1 on 2021-02-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_auto_20210216_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmaster',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
