# Generated by Django 3.1.1 on 2021-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_auto_20210219_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermaster',
            name='owner_pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parentsmaster',
            name='Parents_pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quary_form',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schoolmaster',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staffmaster',
            name='staff_pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
