# Generated by Django 3.1.1 on 2021-02-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_auto_20210223_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmaster',
            name='principal_sign_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
