# Generated by Django 3.1.1 on 2021-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_schoolmaster_principal_sign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermaster',
            name='owner_date_of_birth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
