# Generated by Django 3.1.1 on 2021-02-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_auto_20210228_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownermaster',
            name='owner_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ownermaster',
            name='owner_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
