# Generated by Django 3.1.1 on 2021-03-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_auto_20210228_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmaster',
            name='logo_of_school',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
