# Generated by Django 3.1.1 on 2021-03-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_schoolmaster_logo_of_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_machine_update',
            name='machine_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
