# Generated by Django 3.1.1 on 2021-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_auto_20210306_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_machine_update',
            name='machine_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school_machine_api',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school_machine_api',
            name='ssid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school_machine_update',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school_machine_update',
            name='ssid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
