# Generated by Django 3.1.1 on 2021-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_remove_school_machine_update_machine_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_machine_update',
            name='machine_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
