# Generated by Django 3.1.1 on 2021-03-18 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_school_machine_update_machine_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='busmap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_no', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('school_code', models.CharField(blank=True, max_length=200, null=True)),
                ('rf_id', models.CharField(blank=True, max_length=64, null=True)),
                ('lat', models.CharField(blank=True, max_length=64, null=True)),
                ('log', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.CharField(blank=True, max_length=64, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
