# Generated by Django 3.1.1 on 2021-03-20 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_busmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busapi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_no', models.CharField(blank=True, max_length=200, null=True)),
                ('school_code', models.CharField(blank=True, max_length=100, null=True)),
                ('rf_id', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
