# Generated by Django 3.1.1 on 2021-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_busapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='busapi',
            name='time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='busapi',
            name='date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
