# Generated by Django 3.1.1 on 2021-03-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_auto_20210320_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='busapi',
            name='dealer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
