# Generated by Django 3.1.1 on 2021-03-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_busapi_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busapi',
            name='dealer',
        ),
    ]
