# Generated by Django 3.1.1 on 2021-03-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_remove_busapi_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_transport',
            name='gps_sim_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school_transport',
            name='reader_machine_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
