# Generated by Django 3.1.1 on 2021-03-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_auto_20210320_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_transport',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school_transport',
            name='ssid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
