# Generated by Django 3.1.5 on 2021-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_auto_20210410_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsrestapi',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gpsrestapi',
            name='created_on',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
