# Generated by Django 3.0.8 on 2021-11-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_auto_20210410_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
