# Generated by Django 3.2 on 2022-12-08 15:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_modelwithimage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[640, 480], upload_to='images/'),
        ),
    ]
